export SITE = test.yml
export IMAGE_NAME = debian-ssh
export DOCKER_USER = root
export name = ctx1

define trap
trap 'cat $(container_id) | xargs docker rm -f -v || true ; \
  docker ps -f status=exited -a -q | xargs docker rm -f -v || true ; \
  rm -rf $(container_id); ' KILL TERM EXIT;
endef
export trap
