install:
	# Check ansible version
	ansible --version

	# Create ansible.cfg with correct roles_path
	printf '[defaults]\nroles_path=../' >ansible.cfg

	# Install the additional Ansible roles that are required for testing this one.
	#ansible-galaxy install -r install_roles.yml
