---
- shell: whoami
  register: whoami
  changed_when: False

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: upgrade the distro
  apt: upgrade=dist
  become: yes
