---
- name: Test display myvar
  shell: echo '{{ myvar }}'
  changed_when: False
- name: Test sleep
  shell: sleep '{{ item }}'
  with_items:
    - 2
  changed_when: False
- name: Create debug
  template:
    src: dump_variables
    dest: "/tmp/{{inventory_hostname}}_ansible_variables"
