---
- name: Test display myvar
  shell: echo '{{ myvar }}'
- name: Test sleep
  shell: sleep '{{ item }}'
  with_items:
    - 10
- name: Create debug
  template:
    src: dump_variables
    dest: "./{{inventory_hostname}}_ansible_variables"
