- project:
    name: playbook
    distrib:
      - debian
    target:
      - debian-ansible2:
          previous: 'debian'
      - java:
          previous: 'debian-ansible2'
      - debian-jenkins2:
          previous: 'java'
    jobs:
      - build-{name}-{distrib}

- job-template:
    name: 'build-{name}-{distrib}'
    parameters:
      - string:
          name: PYTHONUNBUFFERED
          default: '1'
          description: "A parameter named PYTHONUNBUFFERED, defaults to '1'."
    scm:
      - ansible-samples
    wrappers:
      - ansicolor
      - timestamps
    builders:
      - ansible-playbook-generate-vars-file
      - ansible-playbook-generate-shell
      - run-sudo
#      - ansible-playbook-run
#      - ansible-playbook-output
#      - ansible-playbook

- scm:
    name: ansible-samples
    scm:
      - git:
         url: https://github.com/pli01/ansible-samples
         branches:
          - origin/master

- builder:
    name: ansible-playbook-generate-vars-file
    builders:
      - shell:
          !include-raw: scripts/ansible-playbook-generate-vars-file.sh

- builder:
    name: ansible-playbook-run
    builders:
      - shell:
          !include-raw: scripts/ansible-playbook-run.sh

- builder:
    name: ansible-playbook-output
    builders:
      - shell:
          !include-raw: scripts/ansible-playbook-output-log.sh

- builder:
    name: ansible-playbook
    builders:
      - shell:
          !include-raw: scripts/ansible-playbook.sh

- builder:
    name: ansible-playbook-generate-shell
    builders:
      - shell:
          !include-raw: scripts/ansible-playbook-generate-shell.sh

- builder:
    name: run-sudo
    builders:
      - shell:
          !include-raw: scripts/run-sudo.sh
